title: Slides Inna Box
email: tamara@tamouse.org
description: >-
  A test of an idea - putting a reveal presentation inside a standard
  C-shaped web site (header, left sidebar nav, footer; with main being
  the slide deck).

collections:
  - slides

# Build settings
source: src
destination: dist
markdown: kramdown

# URLs for using CDN scripts and styles
cdn:
  jquery: "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"
  revealjs: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.5.0/js/reveal.min.js"
  revealcss: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.5.0/css/reveal.min.css"
  zenburncss: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.5.0/lib/css/zenburn.min.css"
  moon_theme: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.5.0/css/theme/moon.min.css"
